// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIWmLYTZ3qYDsVfn_duXEO4c6bW3rbU5Y',
    appId: '1:565656699362:web:a36719668f18b41408b9bb',
    messagingSenderId: '565656699362',
    projectId: 'foodhub-ec4e6',
    authDomain: 'foodhub-ec4e6.firebaseapp.com',
    storageBucket: 'foodhub-ec4e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNNHTF3UnX_VRU4HbbpH8ggpDtYl3-QvY',
    appId: '1:565656699362:android:001b5fb70e132dd508b9bb',
    messagingSenderId: '565656699362',
    projectId: 'foodhub-ec4e6',
    storageBucket: 'foodhub-ec4e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC313ssrCGsKCfrywv-p-WcurUoi8APCu8',
    appId: '1:565656699362:ios:82c2455495f803d408b9bb',
    messagingSenderId: '565656699362',
    projectId: 'foodhub-ec4e6',
    storageBucket: 'foodhub-ec4e6.appspot.com',
    iosBundleId: 'com.example.foodHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC313ssrCGsKCfrywv-p-WcurUoi8APCu8',
    appId: '1:565656699362:ios:606762e9b715489a08b9bb',
    messagingSenderId: '565656699362',
    projectId: 'foodhub-ec4e6',
    storageBucket: 'foodhub-ec4e6.appspot.com',
    iosBundleId: 'com.example.foodHub.RunnerTests',
  );
}
